package dns::monitor::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';
use dns::monitor;

my $DB = eris->config('db');

__PACKAGE__->config(
    schema_class => 'dns::monitor::Schema',
	connect_info => [
		$DB->{dsn}, $DB->{user}, $DB->{pass}
	],
);

=head1 NAME

dns::monitor::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<dns::monitor>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<dns::monitor::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.41

=head1 AUTHOR

Brad Lhotsky

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
